env: production
redis:
  host:                               'db01.production.creditcards.org'
  port:                               6379
  password:                           '59e948a0274c434b910200a60c23f447'

