default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: corvus_bid_development

test:
  <<: *default
  database: corvus_bid_test

production:
  <<: *default
  database: corvus_bid_production
  username: corvus_bid
  password: <%= ENV['CORVUS_BID_DATABASE_PASSWORD'] %>

tracker_bid_default: &tracker_bid_default_default
  adapter:  mysql2
  encoding: utf8
  pool:     5
  socket:   /tmp/mysql.sock
  host:     db01.tracker.production.onrampadvertising.com
  database: tracker
  username: tracker_report
  password: oyneru5pxnqakgdkaegtlbwbubulrfLwfFq9ukxd

tracker_bid_development:
  <<: *tracker_bid_default_default
  database: tracker_bid

tracker_bid_test:
  <<: *tracker_bid_default_default
  database: tracker_bid

tracker_bid_staging:
  <<: *tracker_bid_default_default
  database: tracker_bid
  host: db01.staging.creditcards.org

tracker_bid_production:
  <<: *tracker_bid_default_default
  database: tracker_bid
